#!/bin/bash
###############################################################################
#  Copyright (c) 2015 Eclipse Foundation.
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Distribution License v1.0
#  which accompanies this distribution, and is available at
#  http://www.eclipse.org/org/documents/edl-v10.php
#
#  Contributors:
#     Mikael Barbero - initial implementation
###############################################################################

## Copy this script in /etc/init.d

### BEGIN INIT INFO
# Provides:  jar-signing-service
# Required-Start: $local_fs $remote_fs $network
# Should-Start:
# Required-Stop:  $local_fs $remote_fs $network
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:  start the LTS jar signing service
### END INIT INFO


# Modify these variables for the project being configured
# -------------------------------------------------------
export SERVICE_USERNAME="signinguser"
export SERVICE_GROUP="signingusergroup"
export SERVICE_HOME="/path/to/webservice/signing/jar"
export JAVA_HOME="/path/to/jdk1.8.0"

source "/path/to/signing/jar-signing-service-init"

